{{- if (include "neverland.existingSecret" .) }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.keycloak.auth.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: {{ .Values.keycloak.auth.existingSecret }}
      namespace: {{ .Release.Namespace }}
  encryptedData:
    adminPassword: {{ .Values.neverland.passwordSealed }}
{{- end -}}
